<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.wyhao</groupId>
        <artifactId>platform</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>identity</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>身份模块 - 用户身份、认证登录、凭证与个人资料</description>

    <dependencies>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-security</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-justauth</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-captcha-graphic</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-web</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-db</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-fastexcel</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>file-api</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
