<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.wyhao</groupId>
        <artifactId>platform</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>file-api</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>文件服务基础 API - 上传、下载、预览、删除</description>

    <dependencies>
        <!-- 文件核心模块 -->
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>file-service</artifactId>
        </dependency>

        <!-- Web 模块 -->
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-web</artifactId>
        </dependency>

        <!-- Swagger 注解 -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>
    </dependencies>
</project>
