<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.wyhao</groupId>
        <artifactId>cmn-storage</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>cmn-storage-cos</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>腾讯云 COS 存储实现 - 按需引入腾讯云 COS SDK</description>

    <dependencies>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-storage-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.qcloud</groupId>
            <artifactId>cos_api</artifactId>
            <version>5.6.269</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>
