/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/_core/about/': RouteRecordInfo<
      '/_core/about/',
      '/_core/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/authentication/code-login': RouteRecordInfo<
      '/_core/authentication/code-login',
      '/_core/authentication/code-login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/authentication/force-change-password': RouteRecordInfo<
      '/_core/authentication/force-change-password',
      '/_core/authentication/force-change-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/authentication/forget-password': RouteRecordInfo<
      '/_core/authentication/forget-password',
      '/_core/authentication/forget-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/authentication/login': RouteRecordInfo<
      '/_core/authentication/login',
      '/_core/authentication/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/authentication/qrcode-login': RouteRecordInfo<
      '/_core/authentication/qrcode-login',
      '/_core/authentication/qrcode-login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/authentication/register': RouteRecordInfo<
      '/_core/authentication/register',
      '/_core/authentication/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/fallback/coming-soon': RouteRecordInfo<
      '/_core/fallback/coming-soon',
      '/_core/fallback/coming-soon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/fallback/forbidden': RouteRecordInfo<
      '/_core/fallback/forbidden',
      '/_core/fallback/forbidden',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/fallback/internal-error': RouteRecordInfo<
      '/_core/fallback/internal-error',
      '/_core/fallback/internal-error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/fallback/not-found': RouteRecordInfo<
      '/_core/fallback/not-found',
      '/_core/fallback/not-found',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/fallback/offline': RouteRecordInfo<
      '/_core/fallback/offline',
      '/_core/fallback/offline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/profile/': RouteRecordInfo<
      '/_core/profile/',
      '/_core/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/profile/base-setting': RouteRecordInfo<
      '/_core/profile/base-setting',
      '/_core/profile/base-setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/profile/notification-setting': RouteRecordInfo<
      '/_core/profile/notification-setting',
      '/_core/profile/notification-setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/profile/password-setting': RouteRecordInfo<
      '/_core/profile/password-setting',
      '/_core/profile/password-setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/profile/security-setting': RouteRecordInfo<
      '/_core/profile/security-setting',
      '/_core/profile/security-setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/code/generator/': RouteRecordInfo<
      '/code/generator/',
      '/code/generator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/code/generator/modules/gen-config-drawer': RouteRecordInfo<
      '/code/generator/modules/gen-config-drawer',
      '/code/generator/modules/gen-config-drawer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/code/generator/modules/gen-preview-modal': RouteRecordInfo<
      '/code/generator/modules/gen-preview-modal',
      '/code/generator/modules/gen-preview-modal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics/': RouteRecordInfo<
      '/dashboard/analytics/',
      '/dashboard/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics/analytics-trends': RouteRecordInfo<
      '/dashboard/analytics/analytics-trends',
      '/dashboard/analytics/analytics-trends',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics/analytics-visits': RouteRecordInfo<
      '/dashboard/analytics/analytics-visits',
      '/dashboard/analytics/analytics-visits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics/analytics-visits-data': RouteRecordInfo<
      '/dashboard/analytics/analytics-visits-data',
      '/dashboard/analytics/analytics-visits-data',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics/analytics-visits-sales': RouteRecordInfo<
      '/dashboard/analytics/analytics-visits-sales',
      '/dashboard/analytics/analytics-visits-sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics/analytics-visits-source': RouteRecordInfo<
      '/dashboard/analytics/analytics-visits-source',
      '/dashboard/analytics/analytics-visits-source',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/workspace/': RouteRecordInfo<
      '/dashboard/workspace/',
      '/dashboard/workspace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/form/basic': RouteRecordInfo<
      '/demos/form/basic',
      '/demos/form/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/form/modal': RouteRecordInfo<
      '/demos/form/modal',
      '/demos/form/modal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/naive/': RouteRecordInfo<
      '/demos/naive/',
      '/demos/naive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/table/': RouteRecordInfo<
      '/demos/table/',
      '/demos/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log/': RouteRecordInfo<
      '/monitor/log/',
      '/monitor/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log/login-log': RouteRecordInfo<
      '/monitor/log/login-log',
      '/monitor/log/login-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log/operation-log': RouteRecordInfo<
      '/monitor/log/operation-log',
      '/monitor/log/operation-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log/sms-log': RouteRecordInfo<
      '/monitor/log/sms-log',
      '/monitor/log/sms-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/online/': RouteRecordInfo<
      '/monitor/online/',
      '/monitor/online',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/sms/log/': RouteRecordInfo<
      '/monitor/sms/log/',
      '/monitor/sms/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/open/app/': RouteRecordInfo<
      '/open/app/',
      '/open/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/open/app/modules/detail': RouteRecordInfo<
      '/open/app/modules/detail',
      '/open/app/modules/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/open/app/modules/form': RouteRecordInfo<
      '/open/app/modules/form',
      '/open/app/modules/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedule/job/': RouteRecordInfo<
      '/schedule/job/',
      '/schedule/job',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedule/job/edit-drawer': RouteRecordInfo<
      '/schedule/job/edit-drawer',
      '/schedule/job/edit-drawer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedule/log/': RouteRecordInfo<
      '/schedule/log/',
      '/schedule/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/config/': RouteRecordInfo<
      '/system/config/',
      '/system/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/': RouteRecordInfo<
      '/system/dept/',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/dept-drawer': RouteRecordInfo<
      '/system/dept/dept-drawer',
      '/system/dept/dept-drawer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dict/': RouteRecordInfo<
      '/system/dict/',
      '/system/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/file/': RouteRecordInfo<
      '/system/file/',
      '/system/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu/': RouteRecordInfo<
      '/system/menu/',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/notice/': RouteRecordInfo<
      '/system/notice/',
      '/system/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/message/': RouteRecordInfo<
      '/user/message/',
      '/user/message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/profile/': RouteRecordInfo<
      '/user/profile/',
      '/user/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/_core/about/index.vue': {
      routes:
        | '/_core/about/'
      views:
        | never
    }
    'src/views/_core/authentication/code-login.vue': {
      routes:
        | '/_core/authentication/code-login'
      views:
        | never
    }
    'src/views/_core/authentication/force-change-password.vue': {
      routes:
        | '/_core/authentication/force-change-password'
      views:
        | never
    }
    'src/views/_core/authentication/forget-password.vue': {
      routes:
        | '/_core/authentication/forget-password'
      views:
        | never
    }
    'src/views/_core/authentication/login.vue': {
      routes:
        | '/_core/authentication/login'
      views:
        | never
    }
    'src/views/_core/authentication/qrcode-login.vue': {
      routes:
        | '/_core/authentication/qrcode-login'
      views:
        | never
    }
    'src/views/_core/authentication/register.vue': {
      routes:
        | '/_core/authentication/register'
      views:
        | never
    }
    'src/views/_core/fallback/coming-soon.vue': {
      routes:
        | '/_core/fallback/coming-soon'
      views:
        | never
    }
    'src/views/_core/fallback/forbidden.vue': {
      routes:
        | '/_core/fallback/forbidden'
      views:
        | never
    }
    'src/views/_core/fallback/internal-error.vue': {
      routes:
        | '/_core/fallback/internal-error'
      views:
        | never
    }
    'src/views/_core/fallback/not-found.vue': {
      routes:
        | '/_core/fallback/not-found'
      views:
        | never
    }
    'src/views/_core/fallback/offline.vue': {
      routes:
        | '/_core/fallback/offline'
      views:
        | never
    }
    'src/views/_core/profile/index.vue': {
      routes:
        | '/_core/profile/'
      views:
        | never
    }
    'src/views/_core/profile/base-setting.vue': {
      routes:
        | '/_core/profile/base-setting'
      views:
        | never
    }
    'src/views/_core/profile/notification-setting.vue': {
      routes:
        | '/_core/profile/notification-setting'
      views:
        | never
    }
    'src/views/_core/profile/password-setting.vue': {
      routes:
        | '/_core/profile/password-setting'
      views:
        | never
    }
    'src/views/_core/profile/security-setting.vue': {
      routes:
        | '/_core/profile/security-setting'
      views:
        | never
    }
    'src/views/code/generator/index.vue': {
      routes:
        | '/code/generator/'
      views:
        | never
    }
    'src/views/code/generator/modules/gen-config-drawer.vue': {
      routes:
        | '/code/generator/modules/gen-config-drawer'
      views:
        | never
    }
    'src/views/code/generator/modules/gen-preview-modal.vue': {
      routes:
        | '/code/generator/modules/gen-preview-modal'
      views:
        | never
    }
    'src/views/dashboard/analytics/index.vue': {
      routes:
        | '/dashboard/analytics/'
      views:
        | never
    }
    'src/views/dashboard/analytics/analytics-trends.vue': {
      routes:
        | '/dashboard/analytics/analytics-trends'
      views:
        | never
    }
    'src/views/dashboard/analytics/analytics-visits.vue': {
      routes:
        | '/dashboard/analytics/analytics-visits'
      views:
        | never
    }
    'src/views/dashboard/analytics/analytics-visits-data.vue': {
      routes:
        | '/dashboard/analytics/analytics-visits-data'
      views:
        | never
    }
    'src/views/dashboard/analytics/analytics-visits-sales.vue': {
      routes:
        | '/dashboard/analytics/analytics-visits-sales'
      views:
        | never
    }
    'src/views/dashboard/analytics/analytics-visits-source.vue': {
      routes:
        | '/dashboard/analytics/analytics-visits-source'
      views:
        | never
    }
    'src/views/dashboard/workspace/index.vue': {
      routes:
        | '/dashboard/workspace/'
      views:
        | never
    }
    'src/views/demos/form/basic.vue': {
      routes:
        | '/demos/form/basic'
      views:
        | never
    }
    'src/views/demos/form/modal.vue': {
      routes:
        | '/demos/form/modal'
      views:
        | never
    }
    'src/views/demos/naive/index.vue': {
      routes:
        | '/demos/naive/'
      views:
        | never
    }
    'src/views/demos/table/index.vue': {
      routes:
        | '/demos/table/'
      views:
        | never
    }
    'src/views/monitor/log/index.vue': {
      routes:
        | '/monitor/log/'
      views:
        | never
    }
    'src/views/monitor/log/login-log.vue': {
      routes:
        | '/monitor/log/login-log'
      views:
        | never
    }
    'src/views/monitor/log/operation-log.vue': {
      routes:
        | '/monitor/log/operation-log'
      views:
        | never
    }
    'src/views/monitor/log/sms-log.vue': {
      routes:
        | '/monitor/log/sms-log'
      views:
        | never
    }
    'src/views/monitor/online/index.vue': {
      routes:
        | '/monitor/online/'
      views:
        | never
    }
    'src/views/monitor/sms/log/index.vue': {
      routes:
        | '/monitor/sms/log/'
      views:
        | never
    }
    'src/views/open/app/index.vue': {
      routes:
        | '/open/app/'
      views:
        | never
    }
    'src/views/open/app/modules/detail.vue': {
      routes:
        | '/open/app/modules/detail'
      views:
        | never
    }
    'src/views/open/app/modules/form.vue': {
      routes:
        | '/open/app/modules/form'
      views:
        | never
    }
    'src/views/schedule/job/index.vue': {
      routes:
        | '/schedule/job/'
      views:
        | never
    }
    'src/views/schedule/job/edit-drawer.vue': {
      routes:
        | '/schedule/job/edit-drawer'
      views:
        | never
    }
    'src/views/schedule/log/index.vue': {
      routes:
        | '/schedule/log/'
      views:
        | never
    }
    'src/views/system/config/index.vue': {
      routes:
        | '/system/config/'
      views:
        | never
    }
    'src/views/system/dept/index.vue': {
      routes:
        | '/system/dept/'
      views:
        | never
    }
    'src/views/system/dept/dept-drawer.vue': {
      routes:
        | '/system/dept/dept-drawer'
      views:
        | never
    }
    'src/views/system/dict/index.vue': {
      routes:
        | '/system/dict/'
      views:
        | never
    }
    'src/views/system/file/index.vue': {
      routes:
        | '/system/file/'
      views:
        | never
    }
    'src/views/system/menu/index.vue': {
      routes:
        | '/system/menu/'
      views:
        | never
    }
    'src/views/system/notice/index.vue': {
      routes:
        | '/system/notice/'
      views:
        | never
    }
    'src/views/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
    }
    'src/views/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
    }
    'src/views/user/message/index.vue': {
      routes:
        | '/user/message/'
      views:
        | never
    }
    'src/views/user/profile/index.vue': {
      routes:
        | '/user/profile/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
