<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.wyhao</groupId>
        <artifactId>platform</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>notification</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>通知模块 - 站内消息、公告、短信与邮件通知</description>

    <dependencies>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>identity</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>settings</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-web</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-db</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-security</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-fastexcel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.sms4j</groupId>
            <artifactId>sms4j-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.sticki</groupId>
            <artifactId>spel-validator-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
