<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.wyhao</groupId>
        <artifactId>platform</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>cmn-messaging</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>消息基础设施：邮件 / 短信 / WebSocket</description>

    <dependencies>

        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-base</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>platform-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>top.wyhao</groupId>
            <artifactId>cmn-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.sms4j</groupId>
            <artifactId>sms4j-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>

    </dependencies>
</project>
