name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 2. Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
      - name: 3. Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: 4. Install deps & Build
        run: |
          cd ./frontend
          pnpm install --frozen-lockfile
          pnpm run build:naive          
      - name: 5. Upload dist.zip
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./frontend/apps/web-naive/dist.zip
          target: /opt/1panel/www/sites/tide.wyhao.top/
          strip_components：3
      - name: 6. Deploy site
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /opt/1panel/www/sites/tide.wyhao.top/index/*
            unzip /opt/1panel/www/sites/tide.wyhao.top/dist.zip -d opt/1panel/www/sites/tide.wyhao.top/index/
            rm -f /opt/1panel/www/sites/tide.wyhao.top/dist.zip
            
